version: '3'
services:
    node:
        build: .
        restart: always
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 8080:8080
        command: nodemon server.js --watch
        depends_on:
            - db
    db:
        image: mongo:3.4
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER} 
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWD}
        ports:
            - 27017:27017

